export const industries = [
  'Arhitektura',
  'Bankarstvo',
  'Cestovni prijevoz',
  'Edukacija',
  'Energetika',
  'Farmaceutska industrija',
  'Financijske usluge',
  'Građevinarstvo',
  'Hrana i piće',
  'ICT',
  'Industrijska proizvodnja',
  'Informacijske tehnologije',
  'Kemijska industrija',
  'Konzultantske usluge',
  'Marketing',
  'Medicina',
  'Nekretnine',
  'Obrazovanje',
  'Osiguranje',
  'Poljoprivreda',
  'Pravo',
  'Prehrambena industrija',
  'Promet',
  'Računovodstvo',
  'Rudarstvo',
  'Sport',
  'Telekomunikacije',
  'Tekstilna industrija',
  'Transport',
  'Trgovina',
  'Turizam',
  'Ugostiteljstvo',
  'Usluge',
  'Zdravstvo',
];
