import createClient from 'openapi-fetch';

import type { paths } from './types'; // generated by openapi-typescript

export const importer = createClient<paths>({
  baseUrl: process.env.IMPORTER_URL,
});
